name: Comprimir miEPG XML

on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Verificar versión de miEPG.xml
        id: obtener_version
        run: |
         VERSION=$(cat miEPG.xml | sed 's/comprobante miEPG.xml//g' | sed 's/ *//g' | sed 's/<!--.*-->//g' | sed 's/.*versión//g' | sed 's/[^0-9]//g')
         VERSION=$(echo "$VERSION" | tr -d '\n' | sed 's/\.$//')   # limpia saltos de línea y punto final
         echo "La versión de miEPG.xml es: $VERSION"
         echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"


      - name: Comprimir archivo con gzip
        run: |
          mkdir -p comprimido
          cp miEPG.xml miEPG-${{ steps.obtener_version.outputs.VERSION }}.xml
          gzip -c miEPG-${{ steps.obtener_version.outputs.VERSION }}.xml > comprimido/miEPG-${{ steps.obtener_version.outputs.VERSION }}.xml.gz
          rm miEPG-${{ steps.obtener_version.outputs.VERSION }}.xml

      - name: Commit y push del archivo comprimido
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "felisuk"
          git config --global user.email "felisuk@users.noreply.github.com"
          git add comprimido/miEPG-${{ steps.obtener_version.outputs.VERSION }}.xml.gz
          git commit -m "Añadido archivo comprimido miEPG-${{ steps.obtener_version.outputs.VERSION }}.xml.gz" || echo "Sin cambios para commitear"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/felisuk/mREPdrs.git




