name: Comprimir EPG XML

on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Verificar versión de mEPS.xml
        id: obtener_version
        run: |
          VERSION=$(cat mEPG.xml | sed 's/comprobante mEPG.xml//g' | sed 's/ *//g' | sed 's/<!--.*-->//g' | sed 's/.*versión//g' | sed 's/[^0-9.]//g')
          echo "La versión de mEPG.xml es: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Comprimir archivos
        run: |
          mkdir -p comprimido
          zip -r comprimido/mEPS-${{ steps.obtener_version.outputs.VERSION }}.zip mEPG.xml git

